apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Jambonz InfluxDB
    orgId: 1

datasources:
  - name: Prometheus
    uid: carameli-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Jambonz InfluxDB
    uid: jambonz-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    # @jambonz/time-series writes call-detail records to the `cdrs` database.
    database: cdrs
    editable: true
