from __future__ import annotations

import logging
from typing import Protocol, runtime_checkable

logger = logging.getLogger(__name__)


@runtime_checkable
class CarrierProvider(Protocol):
    async def search_numbers(self, area_code: str, count: int) -> list[dict]: ...
    async def provision_number(self, number: str) -> dict: ...
    async def release_number(self, provider_sid: str) -> None: ...
    async def send_sms(self, from_: str, to: str, body: str) -> dict: ...
    async def enable_sms(self, provider_sid: str) -> None: ...
    async def disable_sms(self, provider_sid: str) -> None: ...
    async def get_available_area_codes(self, country: str, state: str | None) -> list[dict]: ...


@runtime_checkable
class CallEngineProvider(Protocol):
    async def initiate_call(self, from_: str, to: str, webhook_url: str, **opts) -> dict: ...
    async def hangup_call(self, call_id: str) -> None: ...
    async def start_recording(self, call_id: str) -> dict: ...
    async def stop_recording(self, call_id: str) -> None: ...
    async def get_call_status(self, call_id: str) -> dict: ...
    async def initiate_voicemail_drop(self, to: str, from_: str, audio_url: str) -> dict: ...
