"""Tests for scripts/check-lock-markers.py (lockfile env-marker gate)."""

from conftest import load_module

clm = load_module("scripts/check-lock-markers.py")

HEALTHY_LOCK = """\
# This file was autogenerated by uv via the following command:
#    uv pip compile --universal --python-version 3.12 requirements.in -o requirements.txt
click==8.3.1
    # via uvicorn
colorama==0.4.6 ; sys_platform == 'win32'
    # via click
uvicorn==0.50.0
    # via -r requirements.in
uvloop==0.22.1 ; platform_python_implementation != 'PyPy' and sys_platform != 'cygwin' and sys_platform != 'win32'
    # via uvicorn
"""

SENTINELS = {
    "uvloop": "sys_platform != 'win32'",
    "colorama": "sys_platform == 'win32'",
}


def test_parse_pins_maps_names_to_line_and_marker():
    pins = clm.parse_pins(HEALTHY_LOCK)
    assert pins["click"] == (3, "")
    assert pins["colorama"][0] == 5
    assert pins["colorama"][1] == "sys_platform == 'win32'"
    assert "sys_platform != 'win32'" in pins["uvloop"][1]


def test_parse_pins_ignores_comments_and_normalizes_names():
    text = "PyWin32==312 ; sys_platform == 'win32'\nredis[hiredis]==5.3.1\n# uvloop==0.1\n"
    pins = clm.parse_pins(text)
    assert pins["pywin32"] == (1, "sys_platform == 'win32'")
    assert pins["redis"] == (2, "")
    assert "uvloop" not in pins


def test_healthy_lock_has_no_violations():
    assert clm.find_violations(HEALTHY_LOCK, "requirements.txt", SENTINELS) == []


def test_bare_pin_is_flagged_with_file_and_line():
    stripped = HEALTHY_LOCK.replace(
        "uvloop==0.22.1 ; platform_python_implementation != 'PyPy' "
        "and sys_platform != 'cygwin' and sys_platform != 'win32'",
        "uvloop==0.22.1",
    )
    violations = clm.find_violations(stripped, "requirements.txt", SENTINELS)
    assert len(violations) == 1
    assert violations[0].startswith("requirements.txt:9:")
    assert "uvloop" in violations[0]
    assert "no marker" in violations[0]


def test_wrong_marker_is_flagged():
    wrong = HEALTHY_LOCK.replace(
        "uvloop==0.22.1 ; platform_python_implementation != 'PyPy' "
        "and sys_platform != 'cygwin' and sys_platform != 'win32'",
        "uvloop==0.22.1 ; platform_python_implementation != 'PyPy'",
    )
    violations = clm.find_violations(wrong, "requirements.txt", SENTINELS)
    assert len(violations) == 1
    assert "sys_platform != 'win32'" in violations[0]


def test_dropped_win32_line_is_flagged_as_missing():
    dropped = "\n".join(
        line for line in HEALTHY_LOCK.splitlines() if not line.startswith("colorama")
    )
    violations = clm.find_violations(dropped, "requirements-dev.txt", SENTINELS)
    assert len(violations) == 1
    assert violations[0].startswith("requirements-dev.txt:1:")
    assert "missing from the lock" in violations[0]
    assert "SENTINELS" in violations[0]


def test_main_passes_against_real_repo_locks(capsys):
    assert clm.main() == 0
    assert "OK" in capsys.readouterr().out


def test_main_reports_fix_hint_on_violation(tmp_path, monkeypatch, capsys):
    (tmp_path / "requirements.txt").write_text("uvloop==0.22.1\n", encoding="utf-8")
    monkeypatch.setattr(clm, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(
        clm, "SENTINELS", {"requirements.txt": {"uvloop": "sys_platform != 'win32'"}}
    )
    assert clm.main() == 1
    out = capsys.readouterr().out
    assert "# fix:" in out
    assert "requirements.txt:1:" in out


def test_main_flags_missing_lock_file(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(clm, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(
        clm, "SENTINELS", {"requirements.txt": {"uvloop": "sys_platform != 'win32'"}}
    )
    assert clm.main() == 1
    assert "not found" in capsys.readouterr().out
