"""Guard the pip lockfile invariant: requirements*.txt are compiled pins, not floors.

The human-edited floors live in requirements*.in; the *.txt files are generated by
`uv pip compile --universal` (see CLAUDE.md > Guardrails > Dependencies). A floor or
unpinned line sneaking back into a .txt means someone hand-edited a lock, which
silently reopens the version-drift class of failures the lockfiles exist to prevent.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# Requirement lines start with a package name; everything else in a compiled file
# is a comment, blank line, or a continuation of a hash/via annotation.
_REQ_LINE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.\[\]-]*\s*(==|>=|<=|>|<|~=|!=|@)")


def _requirement_lines(path: Path) -> list[str]:
    lines = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if _REQ_LINE.match(line):
            lines.append(line)
    return lines


def test_in_files_exist_as_lock_sources() -> None:
    assert (REPO_ROOT / "requirements.in").is_file()
    assert (REPO_ROOT / "requirements-dev.in").is_file()


def test_locks_are_fully_pinned() -> None:
    for name in ("requirements.txt", "requirements-dev.txt"):
        unpinned = [
            line for line in _requirement_lines(REPO_ROOT / name) if "==" not in line
        ]
        assert not unpinned, (
            f"{name} must contain only compiled '==' pins (edit the .in file and "
            f"recompile instead — see CLAUDE.md > Dependencies). Offending: {unpinned}"
        )


def test_locks_cover_linux_only_packages() -> None:
    """A Windows-compiled non-universal lock silently drops Linux-only deps.

    uvloop (pulled by uvicorn[standard] on non-Windows) is the canary: it must be
    present in the runtime lock with its platform marker, which only happens when
    the lock was compiled with --universal.
    """
    text = (REPO_ROOT / "requirements.txt").read_text(encoding="utf-8")
    assert re.search(r"^uvloop==", text, flags=re.MULTILINE), (
        "uvloop missing from requirements.txt — the lock was likely compiled "
        "without --universal on Windows; recompile via the "
        "'Deps: Recompile Python Lockfiles' task"
    )
