import { cleanup } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'

import { EDIT_MODES, SELECTION_KINDS } from '../../skins/comic-book/editor/selection'
import { controlSurface, EDITOR_STATES, renderState } from './editorStates'

// The editor's whole control surface, every state at once, written to a committed file.
//
// `EditorControlSurface.test.tsx` next door asserts a handful of states against lists
// spelled out in the test. That is the right shape for the few properties worth stating
// in prose — it says *why* shapes mode must offer a panel name — but it protects only
// what someone remembered to write down, and a feature added two years from now is
// covered by it only if that author thinks to come here.
//
// This file is the other half: it enumerates the states from `EDIT_MODES` and
// `SELECTION_KINDS` and writes what it finds to `__snapshots__/editor-control-surface.md`.
// Nothing is asserted about which controls *should* exist, so it never has an opinion
// about a redesign — it only insists that a change to the surface is visible.
//
// **Adding a control is one command:** `npm --prefix frontend run test:run -- -u`. The
// snapshot then shows up in the diff as `+ button: Whatever`, and a reviewer sees a
// feature arrive. Losing one shows up as `- text: panel name` against a red test, and a
// reviewer sees a feature leave. That asymmetry is the entire point: both directions are
// cheap, and neither is silent.
//
// It is deliberately not a strict gate. A snapshot that must be hand-edited would make
// every legitimate change to the editor expensive, and an expensive guard gets deleted.

vi.mock('../../skins/comic-book/editor/useToolbarColumns', () => ({
  useToolbarColumns: () => ({ columnCount: 3, width: 710 }),
}))

vi.mock('../../lib/logger', () => ({
  logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn() },
}))

const PREAMBLE = `# The comic-book editor's control surface

Generated by \`src/tests/skins/EditorSurfaceMatrix.test.tsx\` — do not hand-edit.
Regenerate with \`npm --prefix frontend run test:run -- -u\`.

One section per (mode, selection) state, listing every button, field and menu the
toolbar offers in it. A control that disappears from a state it used to be in is a
feature that has become unreachable there, which is how the panel name was lost from
shapes mode; a control that appears is a feature arriving, and should be in the same
diff as the code that added it.
`

/**
 * Both tests below mount the toolbar once per state. That is a couple of seconds on an
 * idle machine and past vitest's 5s default when the rest of the suite is running beside
 * it, so the budget is stated rather than left to chance — the alternative is a guard
 * that goes red for being slow, which is how a guard gets deleted.
 */
const EVERY_STATE_TIMEOUT_MS = 60_000

describe('the editor control surface, state by state', () => {
  it('matches the committed inventory', async () => {
    const sections = EDITOR_STATES.map(state => {
      renderState(state)
      const controls = controlSurface()
      cleanup()
      return `## ${state.name}\n\n${controls.map(c => `- ${c}`).join('\n')}\n`
    })

    await expect(`${PREAMBLE}\n${sections.join('\n')}`).toMatchFileSnapshot(
      './__snapshots__/editor-control-surface.md',
    )
  }, EVERY_STATE_TIMEOUT_MS)

  // The matrix is only worth as much as its state list, and that list is derived. Asserted
  // against `EDIT_MODES` and `SELECTION_KINDS` rather than against a copy of them, so that
  // a kind added tomorrow fails here until it is covered — a hand-written expectation
  // would simply agree with a hand-written matrix and check nothing.
  it('covers every mode crossed with every selection kind, and the nothing-selected case', () => {
    for (const mode of EDIT_MODES) {
      expect(
        EDITOR_STATES.some(s => s.mode === mode && s.selected === null),
        `no state covers ${mode} with nothing selected`,
      ).toBe(true)

      for (const kind of SELECTION_KINDS) {
        expect(
          EDITOR_STATES.some(s => s.mode === mode && s.selected?.kind === kind),
          `no state covers ${mode}/${kind}`,
        ).toBe(true)
      }
    }
  })

  // A state that renders nothing operable is almost always a harness fault — a stub too
  // thin for the inspector to reach its data — and it would make the snapshot above look
  // reassuringly stable while covering nothing.
  it('renders an operable toolbar in every state', () => {
    for (const state of EDITOR_STATES) {
      renderState(state)
      const controls = controlSurface()
      cleanup()
      expect(controls.length, `${state.name} offered no controls at all`).toBeGreaterThan(0)
    }
  }, EVERY_STATE_TIMEOUT_MS)
})
